Repository UCF/Main-Site-Utilities-Plugin, pull requests merged in 2021-11, with the labels that each got.

#16 Researchers importer updates
  importers/research-importer.php
  includes/commands.php
Labels: enhancement

#17 Updated documentation on research importer
  README.md
  readme.txt
Labels: documentation

#18 Research Importer Update
  importers/research-importer.php
Labels: bug
